project_id = "modular-scout-345114"
sa="dataproc-cluster-sa"
network = "df-network"
sub_network = "df-subnetwork"
region = "us-central1"
df_instance = "data-fusion-private-instance"
edition = "BASIC"
private_ip_range = "10.20.0.0/14"
df_version = "7.6.0"
label_value = "example_value"
enable_logging = true
private_instance = true
